site_name: Yahya Limouni - DAW
nav:
  - Home: index.md
  - Practica2.1: ./Practicas/practica2/index.md
  - Practica2.2: ./Practicas/practica2.2/index.md

theme:
  name: material  # Use Material theme for MkDocs
  features:
    - navigation.tabs  # Enable tab navigation
    - navigation.top  # Show navigation at the top
    - search.highlight  
    - search.share  
    - navigation.tracking  

  palette:
    scheme: slate
    primary: cyan
    accent: indigo
