name: Update Submodule

on:
  push:
    paths:
      - "Practicas/practica2/**"

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update submodule practica2
      run: |
        git submodule update --remote Practicas/practica2
        git add Practicas/practica2
        git commit -m "Automated update of practica2 submodule"
        git push origin main
